/**
 * RuntimeBinding (U4): one Room's link to a Host Execution Scope and the
 * browser-side controller/lease facts. The Browser pre-generates a unique
 * scopeRequestId; the Host creates the Scope idempotently by requestId, so a
 * retry never produces a second Scope or controller generation.
 */

export type RuntimeBindingState = "creating" | "active" | "closing" | "closed";

export interface RuntimeBinding {
  id: string;
  roomId: string;
  /** Unique idempotency key generated by the Browser before Host create. */
  scopeRequestId: string;
  state: RuntimeBindingState;
  /** Null while creating; filled by the Host create response. */
  hostInstanceId: string | null;
  executionScopeId: string | null;
  /** Fencing token pair, refreshed on takeover with a higher leaseEpoch. */
  controllerId: string | null;
  leaseEpoch: number | null;
  createdAt: string;
  updatedAt: string;
}
