/** Stable accessibility/testing landmarks for the report's explainer view. */
const prefix = "review-explainer";
export const explainerUi = {
  root: prefix,
  fileNav: `${prefix}-file-nav`,
  fileRow: (path: string) => `${prefix}-file-${path}`,
  diff: `${prefix}-diff`,
  hunk: (path: string, index: number) => `${prefix}-hunk-${path}-${index}`,
  line: (side: "old" | "new", path: string, line: number) =>
    `${prefix}-line-${side}-${path}-${line}`,
  comment: (id: string) => `${prefix}-comment-${id}`,
  unanchored: `${prefix}-unanchored`,
  understand: `${prefix}-understand`,
  original: `${prefix}-original`,
  willFix: `${prefix}-decide-will-fix`,
  wontFix: `${prefix}-decide-wont-fix`,
  undecided: `${prefix}-decide-undecided`,
  drawer: `${prefix}-drawer`,
  canvas: `${prefix}-canvas`,
  canvasFallback: `${prefix}-canvas-fallback`,
  suggested: `${prefix}-suggested-code`,
  listFix: `${prefix}-list-fix`,
  listSkip: `${prefix}-list-skip`,
  listUndecided: `${prefix}-list-undecided`,
  layoutUnified: `${prefix}-layout-unified`,
  layoutSplit: `${prefix}-layout-split`,
  generate: `${prefix}-generate`,
  retry: `${prefix}-retry`,
  saveError: `${prefix}-save-error`,
  binary: `${prefix}-binary-status`,
  missing: `${prefix}-missing-status`,
  oldAbsent: `${prefix}-old-absent`,
  identity: `${prefix}-identity`,
  stickyHeader: `${prefix}-sticky-header`,
} as const;
